[package]
name = "comments"
version = "0.1.0"
edition = "2021"
authors = ["Hanyuan Li <work@hanyuone.live>"]

[package.metadata.release]
release = false

[lib]
crate-type = ["cdylib"]

[dependencies]
worker = { version = "0.6", features = ["http", "axum", "d1"] }
worker-macros = { version = "0.6" }
console_error_panic_hook = { version = "0.1.7" }
axum = { version = "0.8.4", features = [
    "json",
    "query",
], default-features = false }
tower-service = "0.3.3"
serde = "1.0.219"
axum-extra = { version = "0.10.1", features = ["cookie"] }
reqwest = { version = "0.12.23", features = ["json"] }
uuid = { version = "1.18.1", features = ["v7", "rng-rand"] }
time = "0.3.43"
oauth2 = { path = "../oauth2-rs" }
web-sys = "0.3.77"

# Currently, `oauth2` and `ring` use an old version of `getrandom`, which
# breaks. The local versions patch these repos to use the newest version (0.3.3)
# instead.
[patch.crates-io]
ring = { path = "../ring" }
