[package]
name = "comments"
version = "0.1.0"
edition = "2021"
authors = ["Hanyuan Li <work@hanyuone.live>"]

[package.metadata.release]
release = false

[lib]
crate-type = ["cdylib"]

[dependencies]
worker = { version = "0.6", features = ["http", "axum", "d1"] }
worker-macros = { version = "0.6" }
console_error_panic_hook = { version = "0.1.7" }
axum = { version = "0.8.4", features = ["json"], default-features = false }
tower-service = "0.3.3"
serde = "1.0.219"
