DROP TABLE IF EXISTS Users;

DROP TABLE IF EXISTS OAuthState;
DROP TABLE IF EXISTS UserSessions;

DROP TABLE IF EXISTS Posts;
DROP TABLE IF EXISTS Comments;

CREATE TABLE IF NOT EXISTS Users (
    id INTEGER PRIMARY KEY,
    username TEXT NOT NULL UNIQUE,
    avatar_url TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS OAuthState (
    id INTEGER PRIMARY KEY,
    csrf_token TEXT NOT NULL UNIQUE,
    pkce_verifier TEXT NOT NULL,
    return_url TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS UserSessions (
    id TEXT NOT NULL UNIQUE,
    user_id INTEGER NOT NULL,
    created_at INTEGER NOT NULL,
    expires_at INTEGER NOT NULL,
    FOREIGN KEY(user_id) REFERENCES Users(id)
)

CREATE TABLE IF NOT EXISTS Posts (
    id INTEGER PRIMARY KEY,
    name TEXT NOT NULL UNIQUE
);
CREATE TABLE IF NOT EXISTS Comments (
    id INTEGER PRIMARY KEY,
    post_id INTEGER NOT NULL,
    username TEXT NOT NULL,
    contents TEXT NOT NULL,
    FOREIGN KEY(post_id) REFERENCES Posts(id)
);
